name: "build wasm and deploy to gh-pages"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: apt install emcc make
      - name: Build
        run: make
    deploy:
      needs: build
      provider: pages
      skip_cleanup: true
      github_token: ${{ secrets.GITHUB_TOKEN }}
      keep_history: true
      local_dir: dist
      on:
        branch: master
